name: movie_db_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  social_auth_buttons: ^2.0.0-nullsafety.1
  font_awesome_flutter: ^9.1.0
  logger: ^1.1.0

  #GetX
  get: ^4.3.8

  #Social Login
  google_sign_in: ^5.1.1

  #Firebase
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.2
  firebase_remote_config: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

